apiVersion: v2
name: opentelemetry-demo
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: opensearch
  alias: opensearch
  condition: opensearch.enabled
  repository: https://opensearch-project.github.io/helm-charts/
  version: 2.30.0
- name: opentelemetry-demo
  alias: opentelemetry-demo
  condition: opentelemetry-demo.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.33.8