hosts:
  api_servers:
  - ip_addr: 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/m1.vmwarevm/m1.vmx'
    name: m1
  - ip_addr: 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/m3.vmwarevm/m3.vmx'
    name: m3
  - ip_addr: 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/m2.vmwarevm/m2.vmx'
    name: m2
  cluster_nodes:
    masters:
      primary:
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/m1.vmwarevm/m1.vmx'
      secondary:
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/m3.vmwarevm/m3.vmx'
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/m2.vmwarevm/m2.vmx'
    workers:
      generic:
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/w3.vmwarevm/w3.vmx'
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/w2.vmwarevm/w2.vmx'
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/w4.vmwarevm/w4.vmx'
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/w5.vmwarevm/w5.vmx'
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/w1.vmwarevm/w1.vmx'
      - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/w6.vmwarevm/w6.vmx'
  load_balancers:
  - ip_addr: 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/lb2.vmwarevm/lb2.vmx'
    name: lb2
  - ip_addr: 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/lb3.vmwarevm/lb3.vmx'
    name: lb3
  - ip_addr: 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/lb1.vmwarevm/lb1.vmx'
    name: lb1
  other_nodes:
    databases:
    - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/db.vmwarevm/db.vmx'
    dns:
    - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/dns.vmwarevm/dns.vmx'
    nfs:
    - 'Error: The virtual machine is not powered on: /Users/qt/Virtual Machines.localized/nfs.vmwarevm/nfs.vmx'
