alertmanager:
  enabled: true
  replicaCount: 1
  baseURL: "http://alertmanager.q.t"
  automountServiceAccountToken: true
  service:
    type: ClusterIP
    port: 9093
    clusterPort: 9094
  servicePerReplica:
    enabled: false
  ingress:
    enabled: false
  ingressPerReplica:
    enabled: false
  persistence:
    enabled: true
    storageClass: "longhorn-static"
    size: 50Mi
  config:
    enabled: true
  configmapReload:
    enabled: true
