apiVersion: v2
name: nfs-storage
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: nfs-subdir-external-provisioner
  alias: nfs
  condition: nfs.enabled
  repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  version: 4.0.18
  