# apiVersion: v1
# data:
#   Corefile: |-
#     .:53 {
#         errors
#         health {
#             lameduck 5s
#         }
#         ready
#         kubernetes  cluster.local  cluster.local in-addr.arpa ip6.arpa {
#             pods insecure
#             fallthrough in-addr.arpa ip6.arpa
#             ttl 30
#         }
#         prometheus  0.0.0.0:9153
#         forward  . /etc/resolv.conf 10.123.123.253
#         cache  30
#         loop
#         reload
#         loadbalance
#     }
# kind: ConfigMap
# metadata:
#   annotations:
#     meta.helm.sh/release-name: rke2-coredns
#     meta.helm.sh/release-namespace: kube-system
#   creationTimestamp: "2025-02-11T02:39:49Z"
#   labels:
#     app.kubernetes.io/instance: rke2-coredns
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: rke2-coredns
#     helm.sh/chart: rke2-coredns-1.36.102
#     k8s-app: kube-dns
#     kubernetes.io/cluster-service: "true"
#     kubernetes.io/name: CoreDNS
#   name: rke2-coredns-rke2-coredns
#   namespace: kube-system
#   resourceVersion: "102866"
#   uid: 0f6f4606-f394-4af9-9887-64b62d90d9f2