apiVersion: v2
name: grafana
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: alertmanager
  alias: alertmanager
  condition: alertmanager.enabled
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.13.1
- name: grafana
  alias: grafana
  condition: grafana.enabled
  repository: https://grafana.github.io/helm-charts
  version: 8.6.4
- name: loki
  alias: loki
  condition: loki.enabled
  repository: https://grafana.github.io/helm-charts
  version: 6.22.0
