apiVersion: v2
name: grafana
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: alertmanager
  alias: alertmanager
  condition: alertmanager.enabled
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.14.0
- name: grafana
  alias: grafana
  condition: grafana.enabled
  repository: https://grafana.github.io/helm-charts
  version: 8.8.4
- name: memcached
  alias: memcached
  condition: memcached.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 7.6.1
- name: loki
  alias: loki
  condition: loki.enabled
  repository: https://grafana.github.io/helm-charts
  version: 6.25.0
