apiVersion: v2
name: jaeger-kafka
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: kafka
  alias: kafka
  condition: kafka.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 31.1.1