apiVersion: v2
name: opentelemetry-demo-dependencies
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: opensearch
  alias: opensearch
  condition: opensearch.enabled
  repository: https://opensearch-project.github.io/helm-charts/
  version: 2.30.0
- name: kafka
  alias: kafka
  condition: kafka.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 31.1.1
- name: valkey
  alias: valkey
  condition: valkey.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.2.1
- name: jaeger
  alias: jaeger
  condition: jaeger.enabled
  repository: https://jaegertracing.github.io/helm-charts
  version: 3.3.3
- name: prometheus
  alias: prometheus
  condition: prometheus.enabled
  repository: https://prometheus-community.github.io/helm-charts
  version: 26.1.0
- name: grafana
  alias: grafana
  condition: grafana.enabled
  repository: https://grafana.github.io/helm-charts
  version: 8.8.2
- name: open-feature-operator
  alias: flagd
  condition: flagd.enabled
  repository: https://open-feature.github.io/open-feature-operator/
  version: v0.8.1
- name: opentelemetry-collector
  alias: opentelemetry-collector
  condition: opentelemetry-collector.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.111.1
