apiVersion: v2
name: opentelemetry-collector
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: opentelemetry-collector
  alias: opentelemetry-collector
  condition: opentelemetry-collector.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.111.0
