worker_types:
  m: memory
  c: compute
  d: disk
  g: generic
ssh_key: '/Users/qt/.ssh/qt'
ssh_user: 'qt'
other_nodes:
  dns: dns
  db: databases
  vpn: vpn
  ldap: ldap
vm_dir: /Users/qt/Virtual Machines.localized