apiVersion: v2
name: jaeger
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: jaeger
  alias: jaeger
  condition: jaeger.enabled
  repository: https://jaegertracing.github.io/helm-charts
  version: 3.3.3
- name: zipkin
  alias: zipkin
  condition: zipkin.enabled
  repository: oci://registry-1.docker.io/bitnamicharts/
  version: 1.0.5
