---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-ca-cert
  namespace: jaeger-opensearch
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: q.t
  secretName: opensearch-ca-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: opensearch-ca
    kind: Issuer
    group: cert-manager.io
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "q.t"
  dnsNames:
  - q.t
  - jaeger-opensearch.q.t
  secretName: opensearch-admin-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: "storepass"
        name: "opensearch-secrets"
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-master-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "q.t"
  dnsNames:
  - q.t
  - jaeger-opensearch.q.t
  secretName: opensearch-master-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: "storepass"
        name: "opensearch-secrets"
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-data-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "q.t"
  dnsNames:
  - q.t
  - jaeger-opensearch.q.t
  secretName: opensearch-data-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: "storepass"
        name: "opensearch-secrets"
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-ingest-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "q.t"
  dnsNames:
  - q.t
  - jaeger-opensearch.q.t
  secretName: opensearch-ingest-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: "storepass"
        name: "opensearch-secrets"
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-coordinating-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "q.t"
  dnsNames:
  - q.t
  - jaeger-opensearch.q.t
  secretName: opensearch-coordinating-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: "storepass"
        name: "opensearch-secrets"
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-ca
  namespace: jaeger-opensearch
spec:
  selfSigned: {}
---
# Source: jaeger/charts/certs/templates/certs.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-issuer-from-ca
  namespace: jaeger-opensearch
spec:
  ca:
    secretName: opensearch-ca-keypair
