kind: Secret
apiVersion: v1
metadata:
  name: cassandra-secrets
  namespace: jaeger
type: Opaque
stringData:
  cassandra-password: root1234
  keystore-password: root1234
  truststore-password: root1234
