alertmanager:
  enabled: true
  fullnameOverride: "alertmanager"
  replicaCount: 1
  servicePerReplica:
    enabled: false
  ingress:
    enabled: false
  ingressPerReplica:
    enabled: false
  persistence:
    enabled: false
  config:
    enabled: true
  configmapReload:
    enabled: true
