traefik:
  enabled: true
  deployment:
    enabled: true
    kind: Deployment
    replicas: 1
  ingressClass:  # @schema additionalProperties: false
    enabled: true
    isDefaultClass: true
  experimental:
    kubernetesGateway:
      enabled: true
  gateway:
    # -- When providers.kubernetesGateway.enabled, deploy a default gateway
    enabled: true
    listeners:
      web:
        port: 8000
        hostname: "traefik.q.t"
  gatewayClass:  # @schema additionalProperties: false
    enabled: true
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.q.t`)
      services:
        - name: api@internal
          kind: TraefikService
      entryPoints: ["web"]
  ports:
    traefik:
      port: 8080
      expose:
        default: true
      exposedPort: 8080
      protocol: TCP
    web:
      asDefault: true
      port: 8000
      expose:
        default: true
      exposedPort: 80
    opensearch-9200:
      port: 9200
      expose:
        default: true
      exposedPort: 9200
    opensearch-9300:
      port: 9300
      expose:
        default: true
      exposedPort: 9300
    opensearch-5601:
      port: 5601
      expose:
        default: true
      exposedPort: 5601
    websecure:
      port: 8443
      expose:
        default: true
      exposedPort: 443
  providers:  # @schema additionalProperties: false
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      allowExternalNameServices: true
      allowEmptyServices: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      allowEmptyServices: true
    kubernetesGateway:
      enabled: true
