apiVersion: v2
name: opentelemetry-system
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: opentelemetry-operator
  alias: opentelemetry-operator
  condition: opentelemetry-operator.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.75.1
- name: opentelemetry-collector
  alias: opentelemetry-collector
  condition: opentelemetry-collector.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.111.0
- name: opentelemetry-ebpf
  alias: opentelemetry-ebpf
  condition: opentelemetry-ebpf.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.1.4
- name: opentelemetry-kube-stack
  alias: opentelemetry-kube-stack
  condition: opentelemetry-kube-stack.enabled
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.3.9
  