apiVersion: v2
name: jaeger
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: cassandra
  alias: cassandra
  condition: cassandra.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.0.5