version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "${PORT:-8888}:${CONTAINER_PORT:-80}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ${VOLUME_SOURCE:-.}:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${CONTAINER_PORT:-80}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qt-stocks-network

networks:
  qt-stocks-network:
    driver: bridge 