# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: traefik-dashboard
# spec:
#   routes:
#   - match: Host(`traefik.example.com`)
#     kind: Rule
#     services:
#     - name: api@internal
#       kind: TraefikService
#     middlewares:
#       - name: auth
# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: auth
# spec:
#   basicAuth:
#     secret: secretName # Kubernetes secret named "secretName"