apiVersion: v2
name: jaeger-opensearch
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: opensearch
  alias: opensearch
  condition: opensearch.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 1.5.4

