kind: Secret
apiVersion: v1
metadata:
  name: opensearch-secrets
  namespace: jaeger-opensearch
type: Opaque
stringData:
  username: admin
  password: QP6LMcoAHA53
  # keypassphrase: root1234
  cookie: root1234
