---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  secretName: opensearch-admin-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-master-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  secretName: opensearch-master-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-data-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  secretName: opensearch-data-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-ingest-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  secretName: opensearch-ingest-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-coordinating-tls
  namespace: jaeger-opensearch
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  secretName: opensearch-coordinating-tls-keypair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-dashboards-tls
  namespace: jaeger-opensearch
spec:
  secretName: opensearch-dashboards-tls-keypair
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - client auth
    - digital signature
    - key encipherment
