# - name: Install basic tools
#   gather_facts: true
#   become: true
#   hosts: all
#   tasks:
#   - name: Update and upgrade apt packages
#     apt:
#       upgrade: yes
#       update_cache: yes
#       cache_valid_time: 86400 #One day
#   - name: Install a list of packages
#     apt:
#       pkg:
#       - net-tools
#   - name: Stop and disable firewalld.
#     service:
#       name: ufw
#       state: stopped
#       enabled: False
- name: Setup load balancer
  gather_facts: true
  become: true
  hosts: load_balancer
  tasks:
  - name: Install HAProxy
    apt:
      pkg:
      - haproxy
  - name: Check if file exists
    stat:
      path: /etc/haproxy/haproxy.cfg.bak
    register: p
  - name: Copy file if not exists
    command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
    when: p.stat.exists == False
  - name: Upload config file
    copy:
      src: ../configs/haproxy_config
      dest: /etc/haproxy/haproxy.cfg
  - name: Restart service
    systemd_service:
      state: restarted
      name: haproxy
