- name: Install basic tools
  gather_facts: true
  hosts: all
  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: Install a list of packages
    apt:
      pkg:
      - net-tools
  - name: Stop and disable firewalld.
    become: true
    service:
      name: ufw
      state: stopped
      enabled: False
- name: Setup load balancer
  gather_facts: true
  hosts: load_balancer
  tasks:
  - name: Install HAProxy
    become: true
    apt:
      pkg:
      - haproxy
  - name: Check if file exists
    stat:
      path: /etc/haproxy/haproxy.cfg.bak
    register: p
  - name: Copy file if not exists
    become: true
    command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
    when: p.stat.exists == False
  - name: Upload config file
    become: true
    copy:
      src: ./haproxy_config
      dest: /etc/haproxy/haproxy.cfg
  - name: Restart service
    become: true
    systemd_service:
      state: restarted
      name: haproxy
