
# https://docs.rke2.io/install/quickstart
# - name: Install RKE 
#   gather_facts: true
#   hosts: all
#   become: true
#   tasks:
#   - name: Get installation script
#     shell: |
#       curl -sfL https://get.rke2.io | sh -
#   - name: Creates config directory 
#     file:
#       path: /etc/rancher/rke2/
#       state: directory
#       mode: 0775
#       recurse: yes
# - name: Start RKE in primary master
#   gather_facts: true
#   become: true
#   hosts: primary_master
#   tasks:
#   - name: Upload config file
#     copy:
#       src: rke2_config_master_pri
#       dest: /etc/rancher/rke2/config.yaml
#   - name: Start the rke2-server service
#     systemd_service:
#       state: started
#       name: rke2-server.service
# - name: Start RKE in secondary masters
#   gather_facts: true
#   become: true
#   hosts: secondary_masters
#   tasks:
#   - name: Upload config file
#     copy:
#       src: rke2_config_master_sec
#       dest: /etc/rancher/rke2/config.yaml
#   - name: Start the rke2-server service
#     systemd_service:
#       state: started
#       name: rke2-server.service
- name: Start RKE in workers
  gather_facts: true
  become: true
  hosts: workers
  tasks:
  - name: Reboot workers
    reboot:
  - name: Upload config file
    copy:
      src: rke2_config_worker
      dest: /etc/rancher/rke2/config.yaml
  - name: Start the rke2-server service
    systemd_service:
      state: started
      name: rke2-server.service