- name: Setup load balancer
  become: true
  hosts: load_balancers
  tasks:
  - name: Get primary network adapter
    set_fact: 
      primary_nic: '{{ item }}'
    loop: '{{ ansible_facts.interfaces }}'
    when: 'item.startswith("ens")'
  - name: Print primary network interface
    debug:
      msg: "{{ primary_nic }}"
  # - name: Install HAProxy
  #   apt:
  #     pkg:
  #     - haproxy
  #     - keepalived
  # - name: Check if file exists
  #   stat:
  #     path: /etc/haproxy/haproxy.cfg.bak
  #   register: p
  # - name: Copy file if not exists
  #   command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
  #   when: p.stat.exists == False
  # - name: Upload config file
  #   copy:
  #     src: ../configs/haproxy/haproxy.cfg
  #     dest: /etc/haproxy/haproxy.cfg
  # - name: Validate HAProxy config
  #   shell: |
  #     setsebool -P haproxy_connect_any=1
  #     haproxy  -c -V -f /etc/haproxy/haproxy.cfg
  # - name: Restart service
  #   systemd_service:
  #     state: restarted
  #     name: haproxy
