- name: Setup load balancer
  become: true
  hosts: load_balancers
  tasks:
  - name: Install HAProxy
    apt:
      pkg:
      - haproxy
  - name: Check if file exists
    stat:
      path: /etc/haproxy/haproxy.cfg.bak
    register: p
  - name: Copy file if not exists
    command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
    when: p.stat.exists == False
  - name: Upload config file
    copy:
      src: ../configs/haproxy/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
  - name: Validate HAProxy config
    shell: haproxy  -c -V -f /etc/haproxy/haproxy.cfg
  - name: Restart service
    systemd_service:
      state: restarted
      name: haproxy
