- name: Install NFS server
  hosts: 'nfs'
  become: true
  tasks:
  - name: Install NFS
    apt:
      pkg:
      - nfs-kernel-server
  - name: Enable NFS service
    systemd_service:
      enabled: true
      name: nfs-kernel-server.service
  - name: Create NFS storage directory
    ansible.builtin.file:
      path: /nfs-storage/rke2
      state: directory
      owner: qt
      group: root
      mode: 0775
      recurse: yes
  - name: Update /etc/exports
    lineinfile:
      dest: /etc/exports
      line: /nfs-storage/rke2 *(rw,async,no_subtree_check,no_root_squash)
  - shell: exportfs -a

