- name: Install RKE 
  gather_facts: true
  hosts: '*masters'
  become: true
  vars:
    local_home: /home/qt
  tasks:
  - name: Reboot
    reboot:
  - name: Get installation script
    shell: curl -sfL https://get.rke2.io | sh -
  - name: Enable the rke2-server service
    systemd_service:
      enabled: true
      state: started
      name: rke2-server.service
  - name: Export binary path
    shell: |
      line='export PATH=/var/lib/rancher/rke2/bin:$PATH'
      grep "$line" /root/.bashrc || echo $line >> /root/.bashrc
      grep "$line" {{ local_home }}/.bashrc || echo $line >> {{ local_home }}/.bashrc
      line='export KUBECONFIG=/etc/rancher/rke2/rke2.yaml'
      grep "$line" /root/.bashrc || echo $line >> /root/.bashrc
      grep "$line" {{ local_home }}/.bashrc || echo $line >> {{ local_home }}/.bashrc
      chmod 444 /etc/rancher/rke2/rke2.yaml
