- name: Upload RKE configs and token
  become: true
  hosts: "*masters,*workers"
  tasks:
  - name: Create RKE config directory 
    file:
      path: /etc/rancher/rke2/
      state: directory
      mode: 0775
      recurse: yes
  - name: Upload RKE config file
    copy:
      src: ../configs/rke2/configs/{{ group_names[0] }}.yaml
      dest: /etc/rancher/rke2/config.yaml
  - name: Upload agent token to all nodes
    copy:
      src: ../configs/rke2/tokens/agent
      dest: /etc/rancher/rke2/agent_token
  - name: Upload server token to master nodes
    copy:
      src: ../configs/rke2/tokens/server
      dest: /etc/rancher/rke2/server_token
    when: '"masters" in group_names[0]'
