- name: Install RKE 
  hosts: '*masters'
  become: true
  tasks:
  - name: Reboot
    reboot:
  - name: Get installation script
    shell: curl -sfL https://get.rke2.io | sh -
  - name: Enable the rke2-server service
    systemd_service:
      enabled: true
      name: rke2-server.service
- name: Start RKE in primary master
  hosts: 'primary_masters'
  become: true
  tasks:
  - name: Enable the rke2-server service in primary masters
    systemd_service:
      state: started
      name: rke2-server.service
- name: Start RKE in secondary masters
  hosts: 'secondary_masters'
  become: true
  tasks:
  - name: Enable the rke2-server service in secondary masters
    systemd_service:
      state: started
      name: rke2-server.service
- name: Prepare Kubeconfig
  hosts: '*masters'
  become: true
  vars:
    local_home: /home/qt
  tasks:
  - name: Export binary path
    shell: |
      line='export PATH=/var/lib/rancher/rke2/bin:$PATH'
      grep "$line" /root/.bashrc || echo $line >> /root/.bash_profile
      grep "$line" {{ local_home }}/.bash_profile || echo $line >> {{ local_home }}/.bash_profile
      line='export KUBECONFIG=/etc/rancher/rke2/rke2.yaml'
      grep "$line" /root/.bash_profile || echo $line >> /root/.bash_profile
      grep "$line" {{ local_home }}/.bash_profile || echo $line >> {{ local_home }}/.bash_profile
      chmod 444 /etc/rancher/rke2/rke2.yaml
