- name: Download kubeconfig
  gather_facts: true
  hosts: primary_masters
  vars:
    local_kubeconfig_dir: '' # location of kubeconfig dir of local/client machine
  become: true
  tasks:
  - name: Upload load balancer ip file
    copy:
      src: ../configs/haproxy/ip_address
      dest: /tmp/loadbalancer_ip
  - name: Upload scripts
    copy:
      src: ../scripts/
      dest: /tmp/scripts
  - name: Modify API server endpoint for kube config
    shell: |
      cd /tmp
      pip install -r scripts/requirements.txt
      python3 scripts/update-kubeconfig-endpoint.py
  - name: Download kubeconfig to local ~/.kube/rke2.yaml
    fetch:
      src: /tmp/rke2.yaml
      dest: "{{ local_kubeconfig_dir }}/.kube/rke2.yaml"
      flat: true
