- name: Prepare Kubeconfig
  hosts: '*masters'
  become: true
  vars:
    local_home: /home/qt
  tasks:
  - name: Copy rke2 config to .kube directory at home
    shell: |
      mkdir -p {{ local_home }}/.kube && cp /etc/rancher/rke2/rke2.yaml {{ local_home }}/.kube/rke2.yaml
      mkdir -p /root/.kube && cp /etc/rancher/rke2/rke2.yaml /root/.kube/rke2.yaml
      chmod 775 {{ local_home }}/.kube/rke2.yaml
      chmod 775 /root/.kube/rke2.yaml
  - name: Export rke2 binaries to path
    shell: |
      line='export PATH=/var/lib/rancher/rke2/bin:$PATH'
      grep "$line" /root/.bashrc || echo $line >> /root/.bashrc
      grep "$line" {{ local_home }}/.bashrc || echo $line >> {{ local_home }}/.bashrc
  - name: Export default kubeconfig path
    shell: |
      line='export KUBECONFIG=/root/.kube/rke2.yaml'
      grep "$line" /root/.bash_profile || echo $line >> /root/.bash_profile
      line='export KUBECONFIG={{ local_home }}/.kube/rke2.yaml'
      grep "$line" {{ local_home }}/.bash_profile || echo $line >> {{ local_home }}/.bash_profile
- name: Download kubeconfig
  gather_facts: true
  hosts: primary_masters
  vars:
    local_kubeconfig_dir: '' # location of kubeconfig dir of local/client machine
  become: true
  tasks:
  - name: Upload load balancer ip file
    copy:
      src: ../configs/haproxy/lb_virtual_ip
      dest: /tmp/loadbalancer_ip
  - name: Upload scripts
    copy:
      src: ../scripts/
      dest: /tmp/scripts
  - name: Modify API server endpoint for kube config
    shell: |
      cd /tmp
      pip install -r scripts/requirements.txt
      python3 scripts/update-kubeconfig-endpoint.py
  - name: Download kubeconfig to local ~/.kube/rke2.yaml
    fetch:
      src: /tmp/rke2.yaml
      dest: "{{ local_kubeconfig_dir }}/.kube/rke2.yaml"
      flat: true
