- name: Prepare Kubeconfig
  hosts: '*masters'
  become: true
  vars:
    local_home: /home/qt
  tasks:
  - name: Export binary path
    shell: |
      line='export PATH=/var/lib/rancher/rke2/bin:$PATH'
      grep "$line" /root/.bashrc || echo $line >> /root/.bash_profile
      grep "$line" {{ local_home }}/.bash_profile || echo $line >> {{ local_home }}/.bash_profile
      line='export KUBECONFIG=/etc/rancher/rke2/rke2.yaml'
      grep "$line" /root/.bash_profile || echo $line >> /root/.bash_profile
      grep "$line" {{ local_home }}/.bash_profile || echo $line >> {{ local_home }}/.bash_profile
      chmod 444 /etc/rancher/rke2/rke2.yaml
- name: Download kubeconfig
  gather_facts: true
  hosts: primary_masters
  vars:
    local_kubeconfig_dir: '' # location of kubeconfig dir of local/client machine
  become: true
  tasks:
  - name: Upload load balancer ip file
    copy:
      src: ../configs/haproxy/lb_virtual_ip
      dest: /tmp/loadbalancer_ip
  - name: Upload scripts
    copy:
      src: ../scripts/
      dest: /tmp/scripts
  - name: Modify API server endpoint for kube config
    shell: |
      cd /tmp
      pip install -r scripts/requirements.txt
      python3 scripts/update-kubeconfig-endpoint.py
  - name: Download kubeconfig to local ~/.kube/rke2.yaml
    fetch:
      src: /tmp/rke2.yaml
      dest: "{{ local_kubeconfig_dir }}/.kube/rke2.yaml"
      flat: true
