- name: Setup RKE in workers
  gather_facts: true
  become: true
  hosts: '*workers'
  tasks:
  - name: Reboot
    reboot:
  - name: Get installation script
    shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
  - name: Enable the rke2-agent service
    systemd_service:
      enabled: true
      state: started
      name: rke2-agent.service
