version: '3.8'

services:
  web:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/qtstocks
    depends_on:
      - db
    command: flask run --host=0.0.0.0

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qtstocks
    ports:
      - "5432:5432"

volumes:
  postgres_data: 