version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
      - "5678:5678"  # Debug port
    volumes:
      - .:/app:delegated
      - ./logs:/app/logs
      - /app/venv
      - /app/__pycache__
      - /app/*.pyc
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/qtstocks
      - PYTHONPATH=/app
    depends_on:
      - db
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run --host=0.0.0.0 --port=5555 --reload

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qtstocks
    ports:
      - "5432:5432"

volumes:
  postgres_data: 