apiVersion: v2
name: minio
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: minio
  alias: minio
  condition: minio.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.10.4
