---
kind: Secret
apiVersion: v1
metadata:
  name: opensearch-secrets
  namespace: opensearch-jaeger
type: Opaque
stringData:
  keystore-password: root1234
---
kind: Secret
apiVersion: v1
metadata:
  name: zipkin-secrets
  namespace: jaeger
type: Opaque
stringData:
  keystore-password: root1234
