# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nettools
# spec:
#   containers:
#   - name: nettools
#     image: jrecord/nettools:latest
#     command:
#       - /bin/sh/sleep
#       - "3600"
#     imagePullPolicy: IfNotPresent
#   restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always