---
kind: Secret
apiVersion: v1
metadata:
  name: opensearch-secrets
  namespace: jaeger-opensearch
type: Opaque
stringData:
  # opensearch dashboard secrets
  username: admin
  password: root1234
  cookie: root1234
  # opensearch tls and passwords
  storepass: root1234
  keystore-password: root1234
  truststore-password: root1234
  logstash-password: root1234
  opensearch-password: root1234
  opensearch-dashboards-password: root1234
---
kind: Secret
apiVersion: v1
metadata:
  name: cassandra-secrets
  namespace: jaeger-cassandra
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "jaeger,jaeger-cassandra"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "jaeger,jaeger-cassandra"
type: Opaque
stringData:
  cassandra-password: root1234
  storepass: root1234
  keystore-password: root1234
  truststore-password: root1234
---
kind: Secret
apiVersion: v1
metadata:
  name: zipkin-secrets
  namespace: jaeger
type: Opaque
stringData:
  storepass: root1234
