alertmanager: 
  enabled: true
  replicaCount: 1
  baseURL: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 9093
    clusterPort: 9094
  persistence:
    enabled: false
    storageClass: "longhorn-static"
    accessModes:
      - ReadWriteOnce
    size: 50Mi

  config:
    enabled: true
    templates:
      - '/etc/alertmanager/*.tmpl'
    receivers:
      - name: default-receiver
        # slack_configs:
        #  - channel: '@you'
        #    send_resolved: true
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
  configmapReload:
    enabled: true
  templates: {}
  #   alertmanager.tmpl: |-

