---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: network-system
spec:
  addresses:
  - 192.168.19.200-192.168.19.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: network-system
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  # annotations:
  #   metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80