---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: minio
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`minio.q.t`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: minio
      port: minio-console
  - match: Host(`minio.q.t`) && PathPrefix(`/api/`)
    kind: Rule
    services:
    - name: minio
      port: minio-api
