apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default # Only the store with the name default is taken into account
  namespace: network-system
spec:
  certificates:                          
    - secretName: cassandra-tls-keypair
    - secretName: opensearch-dashboards-tls-keypair
    - secretName: zipkin-tls-keypair
    - secretName: opensearch-tls-keypair
