---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-selfsigned
  namespace: jaeger
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: jaeger
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: q.t
  secretName: opensearch-ca-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: opensearch-selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opensearch-issuer-from-ca
  namespace: jaeger
spec:
  ca:
    secretName: opensearch--ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-for-opensearch
  namespace: jaeger
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  secretName: tls-for-opensearch-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-for-opensearch-dashboards
  namespace: jaeger
spec:
  secretName: tls-for-opensearch-dashboards-key-pair
  issuerRef:
    name: opensearch-issuer-from-ca
    kind: Issuer
    group: cert-manager.io
  commonName: q.t
  dnsNames:
  - q.t
  - jaeger.q.t
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - client auth
    - digital signature
    - key encipherment
