- name: Import variables
  hosts: localhost
  tasks:
  - include_vars: ../configs/vars/pihole.yaml
- name: Install pihole
  import_playbook: subs/install-pihole.yaml
  when: hostvars.localhost.pihole.enabled
- name: Uninstall pihole
  import_playbook: subs/remove-pihole.yaml
  when: not hostvars.localhost.pihole.enabled
- name: Reboot DNS server
  hosts: 'dns'
  become: true
  tasks:
  - reboot: