- name: Install NFS server
  hosts: 'nfs'
  become: true
  tasks:
  - name: Install NFS
    apt:
      pkg:
      - nfs-kernel-server
  - name: Enable NFS service
    systemd_service:
      enabled: true
      name: nfs-kernel-server.service
  - name: Create NFS storage directory
    file:
      path: /nfs-storage/rke2
      state: directory
      recurse: yes
  - shell: |
    chown nobody:nogroup /nfs-storage/rke2
    chmod -R 777 /nfs-storage/rke2
  - name: Update /etc/exports
    lineinfile:
      dest: /etc/exports
      line: /nfs-storage/rke2 *(rw,sync,no_root_squash,insecure,no_subtree_check)
  - shell: exportfs -a
