apiVersion: v2
name: prometheus
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: kube-prometheus-stack
  alias: kube-prometheus-stack
  condition: kube-prometheus-stack.enabled
  repository: https://prometheus-community.github.io/helm-charts
  version: 67.5.0
- name: prometheus
  alias: prometheus
  condition: prometheus.enabled
  repository: https://prometheus-community.github.io/helm-charts
  version: 26.0.1
- name: alertmanager
  alias: alertmanager
  condition: alertmanager.enabled
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.13.1
