apiVersion: v2
name: network-system
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
# load balancer
- name: metallb
  alias: metallb
  condition: metallb.enabled
  repository: https://metallb.github.io/metallb
  version: 0.14.9
# cert manager
- name: cert-manager
  alias: cert-manager
  condition: cert-manager.enabled
  repository: https://charts.jetstack.io
  version: v1.16.2
# ingress controller
- name: traefik
  alias: traefik
  condition: traefik.enabled
  repository: https://traefik.github.io/charts
  version: 34.1.0
