apiVersion: v2
name: jaeger
description: Basic charts
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
# - name: tls-certs
#   alias: certs
#   version: "0.1.0"
#   repository: "file://./custom-charts/tls-certs"
- name: opensearch
  alias: opensearch
  condition: opensearch.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 1.5.4
- name: cassandra
  alias: cassandra
  condition: cassandra.enabled
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.0.5
- name: jaeger
  alias: jaeger
  condition: jaeger.enabled
  repository: https://jaegertracing.github.io/helm-charts
  version: 3.4.0
- name: zipkin
  alias: zipkin
  condition: zipkin.enabled
  repository: https://zipkin.io/zipkin-helm
  version: 0.3.4
- name: opentelemetry-collector
  alias: opentelemetry-collector
  version: 0.111.2
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
